export const tweetsData = [
    {
        tweetName: `NFT Lover💎`,
        handle: `@TrollBot66756542`,
        certification: ``,
        profilePic: `images/troll.jpg`,
        likes: 27,
        retweets: 10,
        tweetText: `Buy Bitcoin, ETH Make 💰💰💰 low low prices. 
            Guaranteed return on investment. HMU DMs open!!`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
    },
    {
        tweetName: `Supreme Chief`,
        handle: `@Elon`,
        certification: `<i class='bx bxs-badge-check'></i>`,
        profilePic: `images/musk.png`,
        likes: 6500,
        retweets: 234,
        tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀 #supremeChiefOfTwitter`,
        replies: [
            {
                tweetName: `Tom Cruise`,
                handle: `@TomCruise`,
                certification: `<i class='bx bxs-badge-check'></i>`,
                profilePic: `images/tcruise.png`,
                tweetText: `Yes! Sign me up! 😎🛩`,
            },
            {
                tweetName: `Chuck Norris`,
                handle: `@ChuckNorris`,
                certification: `<i class='bx bxs-badge-check'></i>`,
                profilePic: `images/chucknorris.jpeg`,
                tweetText: `I went last year😴`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
    },
    {
        tweetName: `Steve Jobless`,
        handle: `@ConfusedCoder`,
        certification: ``,
        profilePic: `images/confused.jpg`,
        likes: 10,
        retweets: 3,
        tweetText: `Are you a coder if you only know HTML?`,
        replies: [
            {
                tweetName: `Coder Downer ☣️`,
                handle: `@StackOverflower`,
                certification: ``,
                profilePic: `images/overflow.png`,
                tweetText: `No. Onviosuly not. Go get a job in McDonald's.`,
            },
            {
                tweetName: `Bob Lovelace`,
                handle: `@YummyCoder64`,
                certification: ``,
                profilePic: `images/bobLovelace.jpg`,
                tweetText: `You are wonderful just as you are! ❤️ #SendingPositiveLinesOfCode`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
    },
]
